{
    "title": "",
    "content": [
        {
            "component": "HomeBanner",
            "props": {
                "bg-img": "/bg2.png",
                "heading": "City Logistics for the Urban Economy",
                "text": "Urban informatics provides the technology foundation for understanding, planning and controlling complex urban transportation systems and is the foundation for all work undertaken within the iCity program.",
                "link": {
                    "label": "Learn more",
                    "href": "/About"
                }
            }
        },
        {
            "component": "Stats",
            "props": {
                "stats": [
                    {
                        "number": 10,
                        "name": "Projects",
                        "href": "/Projects"
                    },
                    {
                        "number": 57,
                        "name": "Publications",
                        "href": "/Projects"
                    },
                    {
                        "number": 5,
                        "name": "Research Themes",
                        "href": "/Research Themes"
                    },
                    {
                        "number": 100,
                        "name": "Researchers",
                        "href": "/Researchers"
                    }
                ]
            }
        },
        {
            "component": "Heading",
            "props": {
                "heading": "Research Theme 1"
            }
        },
        {
            "component": "ItemGroupSummary",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                "href": "/Research Themes/Urban Informatics",
                "items": [
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Cyber-Physical Social ATIS Platform",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    }
                ]
            }
        },
        {
            "component": "ItemSummary",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                "href": "/Research Themes/Urban Informatics",
                "img": "/bg2.png"
            }
        },
        {
            "component": "ItemSummaryGroup",
            "props": {
                "items": [
                    {
                        "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "href": "/Research Themes/Urban Informatics",
                        "img": "/bg2.png"
                    },
                    {
                        "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "href": "/Research Themes/Urban Informatics",
                        "img": "/bg2.png"
                    },
                    {
                        "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "href": "/Research Themes/Urban Informatics",
                        "img": "/bg2.png"
                    }
                ]
            }
        },
        {
            "component": "TextGroup",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "intro": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community.",
                "texts": [
                    "Integrated urban models represent the interactions between transportation and land use evolution in a comprehensive, coordinated way so that the impacts of transportation accessibility on land development and household and firm location processes can be assessed, with these urban form processes, in turn, determining the spatial pattern of travel demand. Integrated urban models provide practical platforms for “systems of systems” modelling of urban spatial-temporal socio-economic processes (travel, housing markets, demographics, etc.) in support of a wide variety of transportation and land use policy analyses.",
                    "ILUTE (Integrated Land Use, Transportation, Environment) model system is a state-of-the-art agent-based, microsimulation system for the GTHA, and the agent-based, activity-based travel microsimulation model TASHA (Travel/Activity Scheduler for Household-Agents), both developed at UofT, provide a cutting-edge platform for urban systems analysis and decision-support. This project took ILUTE/TASHA as its foundation for the development of economic performance measures for improved policy analysis and decision-making three related applications:",
                    "1. A transportation Benefit/Cost Analysis framework to inform transportation investment policy development. ",
                    "2. Integrated modelling capacity to assess the viability and revenue generating potential of different Land Value Capture tools that can be piloted using live transportation investment proposals drawn from the GTHA (e.g. public land development, tax increment financing). ",
                    "3. A dynamic model to assess the costs of different forms of development (e.g., greenfield versus brownfield, or higher versus lower rates of density)."
                ]
            }
        },
        {
            "component": "TextSection",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                "href": "/About"
            }
        },
        {
            "component": "TextSectionPair",
            "props": {
                "first": {
                    "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                    "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                    "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                    "href": "/About"
                },
                "second": {
                    "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                    "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                    "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                    "href": "/About"
                }
            }
        },
        {
            "component": "TextSectionImg",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                "img": "/bg2.png"
            }
        },
        {
            "component": "TextSectionImgGroup",
            "props": {
                "sections": [
                    {
                        "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "img": "/bg2.png"
                    },
                    {
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "img": "/bg2.png"
                    },
                    {
                        "text": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                        "img": "/bg2.png"
                    }
                ]
            }
        },
        {
            "component": "ItemGroup",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "items": [
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Cyber-Physical Social ATIS Platform",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Cyber-Physical Social ATIS Platform",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    },
                    {
                        "heading": "Ontology for Urban Modelling & Design",
                        "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                        "img": "/bg2.png",
                        "href": "/Projects/Ontology for Urban Modelling & Design"
                    }
                ]
            }
        },
        {
            "component": "PeopleGroup",
            "props": {
                "heading": "Primary Investigators",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "people": [
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    },
                    {
                        "name": "Eric J. Miller",
                        "title": "Principle Investigator, iCity",
                        "bio": "Professor Eric Miller is a pioneer in the development and application of agent-based microsimulation model systems in large urban contexts. As director of the University of Toronto Transportation Research Institute (UTTRI), his research is centered in the implementation of activity-based travel models for use in operational practice. This includes the development of integrated transportation-land use models that permit the analysis of the two-way interaction between transportation systems and urban form. His work serves to improve urban transportation best practices and policy decision-making and, thereby improves the quality of life in urban settings.",
                        "img": "/bg2.png"
                    }
                ]
            }
        },
        {
            "component": "LinkGroup",
            "props": {
                "heading": "Urban Informatics for Transportation Operations, Planning and Decision Making",
                "sub": "Led by Prof. Baher Abdullai & Prof. Mark Fox",
                "intro": "The Transportation Planning Suite of Ontologies (TPSO) provides a common set of terms for unambiguously storing and accessing data. The TSPO are used to organize and describe data within the iCity project, and may be used as means of publishing or sharing data with the research community. The TPSO resolves ambiguities and disagreements between terms by defining a common set of concepts that captures the domain, with agreed-upon definitions. The precise and formal nature of the ontology supports the use of services such as question-answering, inference, and data validation. Based on the definitions, we are able to infer new information that was not originally part of the knowledge base. Mapping data from different projects into the ontology identifies relationships which uncover synergies between the projects, thus illustrating how data from one project may serve to inform the work of another.",
                "links":[
                    {
                        "title":"\"Towards a service-oriented cyber–physical systems of systems for smart city mobility applications\". Future Generation Computer Systems, 79, 575-587.",
                        "sub":"Elshenawy, M., Abdulhai, B., & El-Darieby, M. (2018).",
                        "href":"https://www.researchgate.net/publication/328542824_Towards_Seamlessly_Integrated_Cyber-Physical_Intelligent_Transportation_Systems_of_Systems"
                    },
                    {
                        "title":"\"Towards a service-oriented cyber–physical systems of systems for smart city mobility applications\". Future Generation Computer Systems, 79, 575-587.",
                        "sub":"Elshenawy, M., Abdulhai, B., & El-Darieby, M. (2018).",
                        "href":"FILE(/dummy.json)"
                    },
                    {
                        "title":"\"Towards a service-oriented cyber–physical systems of systems for smart city mobility applications\". Future Generation Computer Systems, 79, 575-587.",
                        "sub":"Elshenawy, M., Abdulhai, B., & El-Darieby, M. (2018).",
                        "href":"FILE(/dummy.json)"
                    },
                    {
                        "title":"\"Towards a service-oriented cyber–physical systems of systems for smart city mobility applications\". Future Generation Computer Systems, 79, 575-587.",
                        "sub":"Elshenawy, M., Abdulhai, B., & El-Darieby, M. (2018).",
                        "href":"FILE(/dummy.json)"
                    },
                    {
                        "title":"\"Towards a service-oriented cyber–physical systems of systems for smart city mobility applications\". Future Generation Computer Systems, 79, 575-587.",
                        "sub":"Elshenawy, M., Abdulhai, B., & El-Darieby, M. (2018).",
                        "href":"FILE(/dummy.json)"
                    }
                ]
            }
        }
    ]
}