{
    "title":"City Logistics for the Urban Economy",
    "description":"",
    "version":"20210630",
    "nav":{
        "logo":"/clueFull.svg",
        "links":["Research Themes","Projects","People","Publications","About"]
    },
    "footer":{
        "logo":"/clueFull.svg",
        "primaryLinks":["Research Themes","Projects","People","Publications","About"],
        "secondaryLinks":["Papers","Events","Presentations","Contact us","Legal"],
        "socialMedia":{
            "Facebook":"https://www.facebook.com/",
            "LinkedIn":"https://www.linkedin.com/",
            "Twitter":"https://www.twitter.com/",
            "YouTube":"https://www.youtube.com/"
        },
        "copyright":"Copyright © 2021 City Logistics for the Urban Economy. All rights reserved."
    },
    "colors": {
        "primary": "#ffffff",
        "secondary": "#f2f2f2",
        "highlight":"#002a5c"
    },
    "font":{
        "title":"Montserrat",
        "text":"Noto Sans",
        "action":"Open Sans"
    }
}